// French word list for Wordle (normalized, no accents)
// 5-letter common French words

export const WORD_LIST_FR = [
  'ABORD', 'ABRIS', 'ABUS', 'ACCES', 'ACHAT', 'ACIDE', 'ACIER', 'ACTIF', 'AIGLE', 'AIGU',
  'AIMER', 'ALLEE', 'ALLER', 'AMANT', 'AMBRE', 'ARMEE', 'ARRET', 'ARBRE', 'ARGENT', 'ARME',
  'ASSEZ', 'ASSURE', 'ATOUT', 'AUTRE', 'AVANT', 'AVOIR', 'AVRIL', 'AZOTE', 'BADGE', 'BAGUE',
  'BAIES', 'BAINS', 'BALLE', 'BANJO', 'BARRE', 'BASES', 'BASSIN', 'BATEAU', 'BATON', 'BEAUX',
  'BEIGE', 'BETON', 'BIAIS', 'BLANC', 'BLOCS', 'BLUES', 'BOEUF', 'BOIRE', 'BONNE', 'BORDS',
  'BOSSE', 'BOUGE', 'BOURG', 'BOXE', 'BRAS', 'BRAVE', 'BREF', 'BRUIT', 'BRUME', 'BUSTE',
  'CABLE', 'CADET', 'CADRE', 'CAFES', 'CAGE', 'CAILLE', 'CAISSE', 'CALME', 'CAMPS', 'CANAL',
  'CANOT', 'CAPER', 'CARGO', 'CARTE', 'CASQUE', 'CASSE', 'CAUSE', 'CAVES', 'CEDER', 'CEINT',
  'CENTS', 'CHAMP', 'CHANT', 'CHAOS', 'CHARGE', 'CHARS', 'CHATS', 'CHAUD', 'CHAUX', 'CHEFS',
  'CHENE', 'CHER', 'CHIEN', 'CHIPS', 'CHOCS', 'CHOIX', 'CHOSE', 'CHUTE', 'CIBLE', 'CIDRE',
  'CINQU', 'CIRCE', 'CLAIR', 'CLASS', 'CLEFS', 'CLIPS', 'CLORE', 'CODES', 'COEUR', 'COINS',
  'COLON', 'COMTE', 'CORDE', 'CORNS', 'CORPS', 'COTES', 'COUDE', 'COUPE', 'COURS', 'COURT',
  'COUTS', 'CRAME', 'CRANE', 'CREER', 'CREME', 'CREPE', 'CRETE', 'CREUX', 'CRIME', 'CRISE',
  'CROIX', 'CRUEL', 'CUBES', 'CUIRE', 'CULTE', 'CYCLE', 'DAMES', 'DANSE', 'DATES', 'DEBAT',
  'DEBUT', 'DECOR', 'DEGRE', 'DELAI', 'DEMIS', 'DENSE', 'DENTS', 'DEPAS', 'DETTE', 'DEUIL',
  'DEVANT', 'DEVIL', 'DIAUX', 'DIETS', 'DIGNE', 'DINER', 'DISCO', 'DIVAN', 'DIVIN', 'DOIGT',
  'DOLCE', 'DOMES', 'DONNE', 'DOREE', 'DOSER', 'DOTER', 'DOUCE', 'DOUER', 'DOUTE', 'DRAME',
  'DRAPS', 'DROIT', 'DROLE', 'DRONE', 'DROPS', 'DUNES', 'DUPRE', 'DUREE', 'DURER', 'ECART',
  'ECHEC', 'ECHOS', 'ECOLE', 'ECRAN', 'ECRIT', 'ECROU', 'ECRUT', 'ECUME', 'EFFET', 'EGALE',
  'EGARD', 'ELANS', 'ELEVE', 'EMAIL', 'EMAUX', 'ENFER', 'ENFIN', 'ENJEU', 'ENTRER', 'ENVIE',
  'EPAIS', 'EPARS', 'EPAUL', 'EPICE', 'EPINE', 'EPOUX', 'ERRER', 'ESCAL', 'ESSOR', 'ETAGE',
  'ETAIN', 'ETALE', 'ETANG', 'ETAT', 'ETHER', 'ETHIC', 'ETIRE', 'ETOIL', 'ETUDE', 'EVEIL',
  'EVENT', 'EVITE', 'EXACT', 'EXCES', 'EXIL', 'EXTRA', 'FABLE', 'FACES', 'FACIL', 'FACON',
  'FAITS', 'FAMIL', 'FARDS', 'FATAL', 'FAUNE', 'FASTE', 'FAUTE', 'FAVES', 'FEMME', 'FENTE',
  'FERME', 'FETES', 'FEUIL', 'FIBRE', 'FICHE', 'FIERE', 'FILET', 'FILLE', 'FILMS', 'FINAL',
  'FIXE', 'FLACE', 'FLCHE', 'FLEAU', 'FLEUR', 'FLOAT', 'FLOTS', 'FLUOR', 'FLUX', 'FOIES',
  'FOIRE', 'FOIS', 'FOLIES', 'FONCE', 'FONDS', 'FONTS', 'FORET', 'FORGE', 'FORME', 'FORTE',
  'FOSSE', 'FOULE', 'FOYER', 'FRAIS', 'FRANC', 'FREIN', 'FRERE', 'FRIRE', 'FROID', 'FRONT',
  'FRUIT', 'FUIR', 'FUMEE', 'FURIE', 'FUSEE', 'FUSIL', 'FUTUR', 'GAGES', 'GAINE', 'GANTS',
  'GARDE', 'GARER', 'GAZER', 'GEANT', 'GELEE', 'GENES', 'GENRE', 'GERME', 'GESTE', 'GILET',
  'GLACE', 'GLOBE', 'GLOIR', 'GOMME', 'GORGE', 'GOSSE', 'GOTER', 'GOUTT', 'GRACE', 'GRADE',
  'GRAIN', 'GRAND', 'GRAVE', 'GRELE', 'GREVE', 'GRIEF', 'GRILL', 'GRISE', 'GROGS', 'GROSS',
  'GROTT', 'GROUP', 'GRUE', 'GUIDE', 'HABIT', 'HAINE', 'HALLE', 'HALTE', 'HASARD', 'HAUTE',
  'HERBE', 'HEROS', 'HETRE', 'HEURE', 'HOMME', 'HONEU', 'HONTE', 'HORSE', 'HOTEL', 'HOUPP',
  'HUILE', 'HUIT', 'HUMOR', 'ICONE', 'IDEAS', 'IDIOT', 'IGNOR', 'IMAGE', 'IMMEU', 'IMPOT',
  'INDEX', 'INDIE', 'INERT', 'INTER', 'IRONI', 'ISOLE', 'ISSUE', 'IVOIRE', 'JAILL', 'JAMBE',
  'JANTE', 'JAPON', 'JARDIN', 'JAUNE', 'JEANS', 'JETEE', 'JETER', 'JETON', 'JEUDI', 'JEUNE',
  'JOINT', 'JOLIE', 'JONCH', 'JOUEE', 'JOUER', 'JOUET', 'JOULE', 'JOURN', 'JOVIAL', 'JOYAU',
  'JUBIL', 'JUCHE', 'JUGER', 'JUIFS', 'JUINS', 'JURAS', 'JUPON', 'JURER', 'JURYS', 'JUSTE',
  'LACHE', 'LAINE', 'LAISS', 'LAMES', 'LAMPE', 'LANCE', 'LANGE', 'LAPINS', 'LARGE', 'LARME',
  'LASER', 'LATIN', 'LATTE', 'LAURIE', 'LAVER', 'LECON', 'LEGAL', 'LEGER', 'LEGUE', 'LENTE',
  'LEONE', 'LESION', 'LETTR', 'LEVER', 'LEVRE', 'LIBRE', 'LIEGE', 'LIENS', 'LIEUX', 'LIGNE',
  'LIGUE', 'LILAS', 'LIMIT', 'LINGE', 'LIONS', 'LIQUI', 'LISSE', 'LISTE', 'LITRE', 'LIVRE',
  'LOCAL', 'LOCAU', 'LOGIS', 'LOINS', 'LOISIR', 'LOMBA', 'LONGS', 'LOPIN', 'LOUER', 'LOUPE',
  'LOURD', 'LOVER', 'LOYAL', 'LOYER', 'LUCID', 'LUEUR', 'LUIRE', 'LUMIE', 'LUNDI', 'LUNAR',
  'LUNES', 'LURON', 'LUTER', 'LUTTE', 'LUXE', 'LYCEE', 'LYNCH', 'LYONS', 'LYRE', 'MACHO',
  'MACON', 'MACRO', 'MAGIE', 'MAIGN', 'MAINS', 'MAIRE', 'MAJOR', 'MALES', 'MAMAN', 'MANCHE',
  'MANGE', 'MANNE', 'MANQU', 'MANTE', 'MAQUE', 'MARCH', 'MARDI', 'MAREE', 'MARGE', 'MARIT',
  'MARNE', 'MARQU', 'MARRE', 'MARSE', 'MASSE', 'MATCH', 'MATER', 'MATIN', 'MATUR', 'MAUDI',
  'MAXIM', 'MECHE', 'MEDIA', 'MEDIE', 'MEFIE', 'MEILL', 'MELEE', 'MELON', 'MEMES', 'MEMOI',
  'MENAC', 'MENER', 'MENSE', 'MENTON', 'MEPRI', 'MERCI', 'MERES', 'MERIL', 'MERIT', 'MERLE',
  'MESUR', 'METAL', 'METER', 'METHO', 'METIE', 'METRE', 'METRO', 'METTE', 'MEULE', 'MIELL',
  'MIETT', 'MIEUX', 'MILIE', 'MILLE', 'MINCE', 'MINER', 'MINES', 'MINIM', 'MINOR', 'MINUT',
  'MIRAD', 'MISEE', 'MISER', 'MIXTE', 'MODEL', 'MODER', 'MODES', 'MOELL', 'MOEUR', 'MOGUL',
  'MOINS', 'MOISE', 'MOITE', 'MOITI', 'MOMIE', 'MONDE', 'MONST', 'MONTE', 'MORAL', 'MORDS',
  'MORNE', 'MORSE', 'MORTA', 'MORUE', 'MOTEU', 'MOTIF', 'MOTOS', 'MOTTE', 'MOUCH', 'MOULE',
  'MOULT', 'MOURI', 'MOUSE', 'MOUSS', 'MOUTO', 'MOYEN', 'MUETS', 'MULTI', 'MUNIT', 'MURAL',
  'MURER', 'MURIR', 'MURMU', 'MUSEE', 'MUSER', 'MUTES', 'MUTIN', 'NABOT', 'NACRE', 'NADIR',
  'NAGER', 'NAIFS', 'NAINS', 'NAISS', 'NANAR', 'NANTI', 'NAPOL', 'NAPPE', 'NARDS', 'NARIS'
]

export const KEYBOARD_ROWS_FR = [
  ['A', 'Z', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P'],
  ['Q', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'M'],
  ['ENTER', 'W', 'X', 'C', 'V', 'B', 'N', '⌫']
]

export function getRandomWordFR(): string {
  return WORD_LIST_FR[Math.floor(Math.random() * WORD_LIST_FR.length)]
}

export function isValidWordFR(word: string): boolean {
  return WORD_LIST_FR.includes(word.toUpperCase())
}
